kind = "web"
previewPath = "/"
title = "Academia"
version = "1.0.0"
id = "artifacts/academia"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 3000

[services.development]
run = "pnpm --filter @workspace/academia run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/academia", "run", "build" ]

[services.production.run]
args = ["pnpm", "--filter", "@workspace/academia", "run", "start"]

[services.env]
PORT = "3000"
